# Site settings
title: Alexander Gassel
tagline: Artist
description: > # this means to ignore newlines until "baseurl:"
  Experience the contemporary paintings of Russian-American artist and designer 
  Alexander Gassel - blending the avant-garde with traditional Russian iconography 
  and combining ancient symbols with contemporary subjects, Gassel creates surrealist 
  works that reflect his cultural heritage alongside his experience of life in America.
baseurl: "" # the subpath of the site
url: "https://alexandergassel.com" # the base hostname & protocol for the site

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             Copyright © <!--copyyears--> AlexanderGassel.com. All Rights Reserved. 
